name = "gateway"
main = "src/index.ts"
compatibility_date = "2022-11-13"

account_id = "__CLOUDFLARE_ACCOUNT_ID__"
workers_dev = true
vars = { DEPTH = 2 }

kv_namespaces = [
  { binding = "RESOLVER", id = "__RESOLVER_KV_ID__", preview_id = "__RESOLVER_KV_PREVIEW_ID__" }
]

[env.staging]
route = "__STAGING_ROUTE_PATTERN__"
vars = { DEPTH = 1, GATEWAY = '__STAGING_ROUTE_FQDN__' }

kv_namespaces = [
  { binding = "RESOLVER", id = "__RESOLVER_KV_ID__" }
]

[env.production]
route = "__PRODUCTION_ROUTE_PATTERN__"
vars = { DEPTH = 1, GATEWAY = '__PRODUCTION_ROUTE_FQDN' }

kv_namespaces = [
  { binding = "RESOLVER", id = "__RESOLVER_KV_ID__" }
]
