name: Deploy Worker
on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  lint:
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch' || github.event_name == 'pull_request'
    uses: ./.github/workflows/lint.yml
# Deploy gateway
  deploy_gateway:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Yarn Dependencies
        run: |
          yarn install
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'  # Adjust the Node.js version as needed
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Cache Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}  # Cache key includes the OS and the yarn.lock file
      - name: Deploy to Cloudflare Account
        # Env vars are set in the repo settings
        env: 
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          RESOLVER_KV_ID: ${{ secrets.RESOLVER_KV_ID }}
          RESOLVER_KV_PREVIEW_ID: ${{ secrets.RESOLVER_KV_PREVIEW_ID }}
        run: |
          sed -i "s/__CLOUDFLARE_ACCOUNT_ID__/${CLOUDFLARE_ACCOUNT_ID}/" ./wrangler.toml
          sed -i "s/__RESOLVER_KV_ID__/${RESOLVER_KV_ID}/" ./wrangler.toml
          sed -i "s/__RESOLVER_KV_PREVIEW_ID__/${RESOLVER_KV_PREVIEW_ID}/" ./wrangler.toml
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler deploy --config ./wrangler.toml
